# Generated by Django 3.1.7 on 2021-05-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0004_auto_20210517_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/products/'),
        ),
    ]
