# Generated by Django 3.1.7 on 2021-05-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0006_auto_20210530_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phon',
        ),
    ]
